### ISSUE TITLE
Correct .gitignore for VisualStudio

### ISSUE THREAD

**Issue by Tmjk** [kinorab/pigject#3]
I think we need to adjust the current .gitignore file so we won't need to solve conflicts on files we don't care (currently everything other than source code and recources).

**Comment by kinorab** [comment]
the declaration file at .gitignore had set for VS, but itself does not work perfectly

**Comment by kinorab** [comment]
Well, I find why we cannot to chance file successfully, when you need to get other file into local file, please close solution and then sync, or it(.VS and .suo)  will block getting file.
