### ISSUE TITLE
stack adding

### ISSUE THREAD

**Issue by kinorab** [kinorab/pigject#4]
After fixing some bug about obstacle working, now we need to build a class to contain dozens of stacks, so "stack.h" may need some help.

**Comment by Tmjk** [comment]
I don't sure what do you mean.
but there is a stack in std
http://www.cplusplus.com/reference/stack/stack/stack/
what do you mean?

**Comment by kinorab** [comment]
I mean the stack is "Brick" or also call "Block", std::stack is used to deal with memory, but I want to deal with GAME!

**Comment by Tmjk** [comment]
I still don't understand what a stack of bricks in game means.

**Comment by kinorab** [comment]
Umm, but I want to use sf::Shape class to derive a new class to build stack.

**Comment by Tmjk** [comment]
So what is a stack ,  is it an obstacle or something?

**Comment by kinorab** [comment]
The stacks which the player should use ball to break them.

**Comment by Tmjk** [comment]
I see , so it's a "brick". That is not what "stack" means though, a "stack" is a pile of something.
And I think a "brick" can be seemed as an extended version of an "block" with additional behaviors like breaking when get hit or something like that.

**Comment by kinorab** [comment]
OK, I see.
