### ISSUE TITLE
Upload change file

### ISSUE THREAD

**Issue by kinorab** [kinorab/pigject#5]
The change interface can choose the necessary file (with right chick dir or file and select temporary save)before uploading all file, and choose temp accepting, so that can avoid .VS.db and .suo blocking the sync interface when getting the sync record.

**Comment by Tmjk** [comment]
okay.

**Comment by kinorab** [comment]
By the way, when we adding new source file or new header file, please save the change of .vcxproj file, so that we don't need to extract them from dir again, vice verse.
